//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class categories
    {
        public int categories_id { get; set; }
        public string categories_image { get; set; }
        public int parent_id { get; set; }
        public bool categories_status { get; set; }
        public string categories_template { get; set; }
        public string group_ids { get; set; }
        public string listing_template { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string products_sorting { get; set; }
        public string products_sorting2 { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
    }
}
