//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_description
    {
        public int products_id { get; set; }
        public int language_id { get; set; }
        public string products_name { get; set; }
        public string products_description1 { get; set; }
        public string products_short_description { get; set; }
        public string products_meta_title { get; set; }
        public string products_meta_description { get; set; }
        public string products_meta_keywords { get; set; }
        public string products_url { get; set; }
        public Nullable<int> products_viewed { get; set; }
    }
}
