//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int products_id { get; set; }
        public int products_quantity { get; set; }
        public int products_shippingtime { get; set; }
        public string products_model { get; set; }
        public string group_ids { get; set; }
        public Nullable<int> products_sort { get; set; }
        public string products_image { get; set; }
        public decimal products_price { get; set; }
        public decimal products_discount_allowed { get; set; }
        public System.DateTime products_date_added { get; set; }
        public Nullable<System.DateTime> products_last_modified { get; set; }
        public Nullable<System.DateTime> products_date_available { get; set; }
        public decimal products_weight { get; set; }
        public bool products_status { get; set; }
        public int products_tax_class_id { get; set; }
        public string product_template { get; set; }
        public string options_template { get; set; }
        public Nullable<int> manufacturers_id { get; set; }
        public int products_ordered { get; set; }
        public int products_fsk18 { get; set; }
        public int products_featured { get; set; }
        public string products_stock_code { get; set; }
        public string products_storage_spaces { get; set; }
        public string products_transport { get; set; }
        public string products_country { get; set; }
        public Nullable<decimal> epass_price { get; set; }
    }
}
